name: CI/CD Pipeline

on:
  push:

jobs:
  workflow:
    name: Workflow
    env:
      DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
      DOCKER_REGISTRY_ID: ${{ secrets.DOCKER_REGISTRY_ID }}
      DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build
        run: ./build.sh
